language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 0.4
  - 0.5
  - 0.6
  - 0.7
  - 0.8
  - 0.9
  - 0.10
branches:
only:
    - dev
    - master
after_success:
    - make coveralls